### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by rexagod**
Correction for larger node projects.

### CODE REVIEW

**Comment by jameshibbard** [comment]
Hi, thanks for the PR. How does this change help larger node projects?

**Comment by rexagod** [comment]
Hi @jameshibbard! Actually it didn't seem to work on my project as it was scoped inside its current folder. Moreover, the relative path to the `service-worker.js` was not correct.

**Comment by jameshibbard** [comment]
OK. Can you pls change `./../service-worker.js` to `../service-worker.js` and I'll merge.

**Comment by jameshibbard** [comment]
Thanks :)

**Pull request merged**
